name: "Build Docker image"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - "src/**"
      - Cargo.toml
      - Cargo.lock
      - Dockerfile
      - .github/workflows/build_image.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CONTAINER_REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
